# Generated by Django 4.1.4 on 2022-12-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_category_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
