# Generated by Django 4.1.4 on 2022-12-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_test_test_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_questions',
        ),
        migrations.AddField(
            model_name='question',
            name='question_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
    ]
