# Generated by Django 4.1.4 on 2022-12-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_test_test_questions_question_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_test',
        ),
        migrations.AddField(
            model_name='test',
            name='test_questions',
            field=models.ManyToManyField(to='tests.question'),
        ),
    ]
